
version: "3.8"

services:
  localstack:
    container_name: localstack-hackathon
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs # Lista de serviços para subir apenas o que precisamos
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init.sh:/docker-entrypoint-initaws.d/00-localstack-init.sh"

  postgres:
    container_name: db-hackathon
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-hackathon
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    container_name: app-hackathon
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: production
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  app-migrations:
    container_name: app-migrations-hackathon
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: production
    entrypoint: ./entrypoints/setup-db.sh

volumes:
  postgres-data:
  redis-data:
  app:
